stages:
  - build
  - remove
  - deploy
  - release
    
Build Bot:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/bot:latest .
    - docker push $CI_REGISTRY_IMAGE/bot:latest
  tags:
    - builder
  only:
    refs:
      - develop
  environment: 
    name: development

Deploy Bot:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f deploy/compose.yml pull
    - docker-compose -f deploy/compose.yml -p tezos-bot up --remove-orphans -d
  tags:
    - deployer
  only:
    refs:
      - develop
  variables:
    DB: "User ID=${DB_USER};Host=db;Password=${DB_PASSWORD};Port=5432;Database=${DB_NAME};Pooling=true;"
    ENV: Staging
    BI_PORT: 50000
    PG_PORT: 50010
    
  environment: 
    name: development
    
Remove Bot:
  stage: remove
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f deploy/compose.yml -p tezos-bot down --remove-orphans -d
  tags:
    - deployer
  only:
    refs:
      - develop
  variables:
    DB: "User ID=${DB_USER};Host=db;Password=${DB_PASSWORD};Port=5432;Database=${DB_NAME};Pooling=true;"
    ENV: Staging
    BI_PORT: 50000
    PG_PORT: 50010

  environment:
    name: development