version: "3.8"
services:
  db:
    image: postgres:12
    restart: unless-stopped 
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
  bot:
    image: $CI_REGISTRY_IMAGE/bot:latest
    restart: unless-stopped
    networks: 
      - default
      - graylog
    depends_on:
      - db
    environment:
      - DOTNET_ENVIRONMENT=$ENV
      - Twitter__AccessToken
      - Twitter__AccessTokenSecret
      - Twitter__ConsumerKey
      - Twitter__ConsumerKeySecret
      - Telegram__BotSecret
      - ConnectionStrings__Default=$DB

  bi:
    image: metabase/metabase
    ports:
      - $BI_PORT:3000
    restart: unless-stopped 
    depends_on:
      - bi-db
    networks:
      - default
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_USER=$BI_DB_USER
      - MB_DB_PASS=$BI_DB_PASSWORD
      - MB_DB_PORT=5432
      - MB_DB_HOST=bi-db
      - MB_DB_DBNAME=$BI_DB_NAME
  bi-db:
    image: postgres:12
    restart: unless-stopped 
    volumes:
      - bi-data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=$BI_DB_NAME
      - POSTGRES_USER=$BI_DB_USER
      - POSTGRES_PASSWORD=$BI_DB_PASSWORD

  db-admin:
    image: dpage/pgadmin4
    ports:
      - $PG_PORT:80
    restart: unless-stopped 
    depends_on:
      - db
    networks:
      - default
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_USER
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD

volumes:
  bi-data:
  app-data:
    
networks:
  default: 
    driver: bridge
  graylog:
    external: 
      name: graylog_graylog
