version: "3.8"
services:
  db:
    image: postgres:12
    restart: unless-stopped 
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
  bot:
    image: $CI_REGISTRY_IMAGE/bot:latest
    restart: unless-stopped
    networks: 
      - default
      - graylog
    depends_on:
      - db
    environment:
      - DOTNET_ENVIRONMENT=$ENV
      - Twitter__AccessToken
      - Twitter__AccessTokenSecret
      - Twitter__ConsumerKey
      - Twitter__ConsumerKeySecret
      - Telegram__BotSecret
      - ConnectionStrings__Default=$DB

  bi:
    image: metabase/metabase
    ports:
      - $BI_PORT:3000
    labels:
      - traefik.http.routers.bi.rule=Host(`bi.test.tnb.thegroup.tech`)
      - traefik.http.services.bi.loadbalancer.server.port=$BI_PORT
    restart: unless-stopped 
    depends_on:
      - bi-db
    networks:
      - default
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_USER=$BI_DB_USER
      - MB_DB_PASS=$BI_DB_PASSWORD
      - MB_DB_PORT=5432
      - MB_DB_HOST=bi-db
      - MB_DB_DBNAME=$BI_DB_NAME
  bi-db:
    image: postgres:12
    restart: unless-stopped 
    volumes:
      - bi-data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=$BI_DB_NAME
      - POSTGRES_USER=$BI_DB_USER
      - POSTGRES_PASSWORD=$BI_DB_PASSWORD

  db-admin:
    image: dpage/pgadmin4:latest
    ports:
      - $PG_PORT:80
    restart: unless-stopped 
    depends_on:
      - db
    networks:
      - default
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_USER
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
  
  tzkt-db:
    image: postgres:12
    volumes:
      - tzkt-data:/var/lib/postgresql/data
    restart: always
    networks:
      - default
    environment:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: tzkt_db_password
      POSTGRES_DB: tzkt_db
      
  tzkt-api:
    image: bakingbad/tzkt-api:$TZKT_VERSION
    restart: always
    depends_on:
      - tzkt-db
    networks:
      - default
    volumes:
      - ${PWD}/deploy/tzkt/api.settings.json:/app/appsettings.json
  
  tzkt-sync:
    image: bakingbad/tzkt-sync:$TZKT_VERSION
    restart: always
    depends_on:
      - tzkt-db
    networks:
      - default
    volumes:
      - ${PWD}/deploy/tzkt/sync.settings.json:/app/appsettings.json
    
volumes:
  bi-data:
  app-data:
  tzkt-data:
    
networks:
  default: 
    driver: bridge
  graylog:
    external: 
      name: graylog_graylog
      